import Head from 'next/head';
import { Basic, Inter } from 'next/font/google';
import { useState, useEffect, useCallback } from 'react';

import dayjs from 'dayjs';

import { Card, CardContent, List, ListItem } from '@/components/mui';

import BasicDatePicker from '@/components/DatePicker';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';

const { BALLDONTLIE_ENDPOINT, BALLDONTLIE_API_KEY } = process.env;

export default function Games({ ssd = [] }) {
  const [listOfGames, setListOfGames] = useState(ssd);

  const [date, setDate] = useState(dayjs(new Date()));

  const fetchGames = async (date) => {
    setDate(date);

    try {
      const formattedDate = date.format('YYYY-MM-DD');

      const response = await fetch(
        `/api/games/fetchGames?date=${formattedDate}`,
      );

      if (!response.ok) {
        throw new Error('Failed to fetch data');
      }
      const data = await response.json();
      setListOfGames(data);
    } catch (error) {
      console.error('Error fetching data:', error);
    }
  };

  const handleDateChange = (date) => {
    fetchGames(date);
  };

  return (
    <>
      <Head>
        <title>Games - NBA Guesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading>Games</Heading>
        <BasicDatePicker dateChange={handleDateChange} date={date} />
        <List component={'ol'} sx={{ listStyle: 'none' }}>
          {listOfGames.length > 0 ? (
            listOfGames.map(({ id, date, home_team, visitor_team }) => (
              <ListItem key={id}>
                <Card component="article" sx={{ width: '100%' }}>
                  <Heading component="h2" variant="h3">
                    {home_team.full_name} vs {visitor_team.full_name}
                  </Heading>
                  <CardContent>{date}</CardContent>
                </Card>
              </ListItem>
            ))
          ) : (
            <ListItem>
              <Card component="article" sx={{ width: '100%' }}>
                <CardContent>No games found</CardContent>
              </Card>
            </ListItem>
          )}
        </List>
      </Layout>
    </>
  );
}

export const getStaticProps = async () => {
  const dateToday = dayjs(new Date()).format('YYYY-MM-DD');
  const gamesToday = await fetch(
    `${BALLDONTLIE_ENDPOINT}games?dates[]=${dateToday}`,
    {
      method: 'GET',
      headers: {
        Authorization: BALLDONTLIE_API_KEY,
      },
    },
  )
    .then((res) => res.json())
    .catch((err) => console.log(err));
  const games = gamesToday.data;
  return {
    props: {
      ssd: games,
    },
  };
};