import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useState, useEffect, useCallback } from 'react';

import {
  Card,
  CardContent,
  DatePicker,
  List,
  ListItem,
} from '@/components/mui';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';

const { BALLDONTLIE_ENDPOINT, BALLDONTLIE_API_KEY } = process.env;

const gamesEndpoint = 'https://api.balldontlie.io/v1/games';

export default function Games({ ssd = [] }) {
  console.log(ssd);
  // const getGamesOnDate = useCallback((getGames) => {
  //   getGames = async () => {
  //     await fetch(`${BALLDONTLIE_ENDPOINT}games`, {
  //       method: 'GET',
  //       headers: {
  //         'Content-Type': `application/json; charset="UTF-8`,
  //         Authorization: BALLDONTLIE_API_KEY,
  //       },
  //     })
  //       .then((res) => res.json())
  //       .catch((err) => console.log(err));
  //   };
  // });

  // useEffect(() => {
  //   fetch('https://api.balldontlie.io/v1/games?dates[]=2024-03-02', {
  //     method: 'GET',
  //     headers: {
  //       Authorization: '11c59173-446b-402c-bc3e-f5e5e0087e37',
  //     },
  //   })
  //     .then((res) => res.json())
  //     .catch((err) => console.log(err))
  //     .then((data) => {
  //       setGames(data.data);
  //     }),
  //     console.log(games);
  //   console.log('test');
  // });

  return (
    <>
      <Head>
        <title>Games - NBA Guesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading>Games</Heading>
        <List component={'ol'} sx={{ listStyle: 'none' }}>
          {ssd.map(({ id, date, home_team, visitor_team }) => (
            <ListItem key={id}>
              <Card component="article" sx={{ width: '100%' }}>
                <Heading component="h2" variant="h3">
                  {home_team.full_name} vs {visitor_team.full_name}
                </Heading>
                <CardContent>{date}</CardContent>
              </Card>
            </ListItem>
          ))}
        </List>
      </Layout>
    </>
  );
}

export const getStaticProps = async () => {
  const gamesToday = await fetch(`${BALLDONTLIE_ENDPOINT}games`, {
    method: 'GET',
    headers: {
      Authorization: BALLDONTLIE_API_KEY,
    },
  })
    .then((res) => res.json())
    .catch((err) => console.log(err));
  const games = gamesToday.data;
  console.log(games);
  return {
    props: {
      ssd: games,
    },
  };
};
