import { useEffect, useState } from 'react';
import Head from 'next/head';
import { useUser } from '@auth0/nextjs-auth0/client';
import axios from 'axios';
import usePostRequest from './api/v1/users/usePostRequest';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';

const Home = () => {
  const { user } = useUser();

  usePostRequest(user);

  return (
    <>
      <Head>
        <title>NBA Guesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading>Home page</Heading>
      </Layout>
    </>
  );
};

export default Home;
