import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';

export default function Home() {
  return (
    <>
      <Head>
        <title>NBA Guesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading>Home page</Heading>
      </Layout>
    </>
  );
}
