import Head from 'next/head';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';

import Table from '@/components/Table';

export default function Leaderboard() {
  const columns = [
    { field: 'id', headerName: 'Ranking', width: 70 },
    { field: 'nickname', headerName: 'Name', width: 70 },
    { field: 'totalGuesses', headerName: 'Total guesses', width: 130 },
    { field: 'correctGuesses', headerName: 'Correct guesses', width: 130 },
    { field: 'accuracy', headerName: 'Success rate', width: 130 },
    {
      field: 'age',
      headerName: 'Age',
      type: 'number',
      width: 90,
    },
    {
      field: 'fullName',
      headerName: 'Full name',
      description: 'This column has a value getter and is not sortable.',
      sortable: false,
      width: 160,
      valueGetter: (params) =>
        `${params.row.firstName || ''} ${params.row.lastName || ''}`,
    },
  ];

  const rows = [
    {
      id: 1,
      nickname: 1,
      totalGuesses: 'Snow',
      correctGuesses: 'Jon',
      accuracy: 35,
    },
    {
      id: 2,
      nickname: 2,
      totalGuesses: 'Lannister',
      correctGuesses: 'Cersei',
      accuracy: 42,
    },
    {
      id: 3,
      nickname: 3,
      totalGuesses: 'Lannister',
      correctGuesses: 'Jaime',
      accuracy: 45,
    },
    {
      id: 4,
      nickname: 4,
      totalGuesses: 'Stark',
      correctGuesses: 'Arya',
      accuracy: 16,
    },
    {
      id: 5,
      nickname: 5,
      totalGuesses: 'Targaryen',
      correctGuesses: 'Daenerys',
      accuracy: null,
    },
    {
      id: 6,
      nickname: 6,
      totalGuesses: 'Melisandre',
      correctGuesses: null,
      accuracy: 150,
    },
    {
      id: 7,
      nickname: 7,
      totalGuesses: 'Clifford',
      correctGuesses: 'Ferrara',
      accuracy: 44,
    },
    {
      id: 8,
      nickname: 8,
      totalGuesses: 'Frances',
      correctGuesses: 'Rossini',
      accuracy: 36,
    },
    {
      id: 9,
      nickname: 9,
      totalGuesses: 'Roxie',
      correctGuesses: 'Harvey',
      accuracy: 65,
    },
  ];

  return (
    <>
      <Head>
        <title>NBA Guesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading>Leaderboard</Heading>
      </Layout>
      <Table rows={rows} columns={columns} />
    </>
  );
}
